# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7b0aa7ece85f28cabaf81084399dad1ef5bcae921ed44d38eaad77cc3872daabbdec039a94c0a2d164439dfaa3d6b14b332c61739d347df0b1ad2c3c4e41f411

test:
  secret_key_base: fe4b8bd5cfc622fb6daf7de90d8f8c697daa4c3f95b38b8cff8d343604256170351bd0ad4d3c44e10730a8093334bee5682548f5b8fc01d3dda0dbcc2c2ade6b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
